=== osu-cass/seagrant-tsunami/src/SeaGrant.Web/XML/SeaGrantVideo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Places">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Place">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Description" type="xs:string" />
              <xs:element name="Videos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Video">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="VideoName" type="xs:string" />
                          <xs:element name="FileName" type="xs:string" />
                          <xs:element name="Description" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== osu-cass/seagrant-tsunami/src/Seagrant.Tsunami.Web/XML/SeaGrantVideo.xml
<?xml version="1.0" encoding="utf-8" ?>
<Places
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="SeaGrantVideo.xsd">
  <Place>
    <Name>South Beach</Name>
    <Description>If you are enjoying the beach near South Beach state Park there are numerous evacuation route you can take in the event of a tsunami event.</Description>
    <Order>1</Order>
    <Videos>
      <Video>
        <VideoName>Jetty</VideoName>
        <FileName>/videos/Blue.mp4</FileName>
        <Description>Even though certain routes look faster, such as the jetty road route, watch the video and see the how the tsunami wave behaves once it enters the mouth of the jetty.</Description>
        <Order>2</Order>
      </Video>
      <Video>
        <VideoName>Automobile Evacuation From Park</VideoName>
        <FileName>/videos/Green.mp4</FileName>
        <Description>Even though certain routes look faster, such as getting in your vehicle, watch the video to see what the ramifications of vehicular evacuation may be.</Description>
        <Order>1</Order>
      </Video>
    </Videos>
  </Place>
  <Place>
    <Name>North Beach</Name>
    <Description>The North Beach</Description>
    <Order>1</Order>
    <Videos>
      <Video>
        <VideoName>Rocks</VideoName>
        <FileName>/videos/Purple.mp4</FileName>
        <Description>Description for Rocks</Description>
        <Order>2</Order>
      </Video>
      <Video>
        <VideoName>Sand</VideoName>
        <FileName>/videos/Yellow.mp4</FileName>
        <Description>Description for Sand</Description>
        <Order>2</Order>
      </Video>
    </Videos>
  </Place>
</Places>

=== osu-cass/seagrant-tsunami/src/SeaGrant.Web/XML/SeaGrantVideo.xml
<?xml version="1.0" encoding="utf-8" ?>

<Places
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="SeaGrantVideo.xsd">
  <Place>
    <Name>South Beach</Name>
    <Description>The South Beach</Description>
    <Videos>
      <Video>
        <VideoName>Jetty</VideoName>
        <FileName>/videos/Blue.mp4</FileName>
        <Description>Description for Jetty</Description>
      </Video>
      <Video>
        <VideoName>ParkingLot</VideoName>
        <FileName>/videos/Green.mp4</FileName>
        <Description>Description for parking lot</Description>
      </Video>
    </Videos>
  </Place>

  <Place>
    <Name>North Beach</Name>
    <Description>The South Beach</Description>
    <Videos>
      <Video>
        <VideoName>Rocks</VideoName>
        <FileName>/videos/Purple.mp4</FileName>
        <Description>Description for Jetty</Description>
      </Video>
      <Video>
        <VideoName>Sand</VideoName>
        <FileName>/videos/Yellow.mp4</FileName>
        <Description>Description for parking lot</Description>
      </Video>
    </Videos>
  </Place>
</Places>
